name: Deploy

on: [push]

jobs:
  deploy:
    name: Laravel Envoy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install Laravel Envoy
        run: composer global require laravel/envoy
      - name: Install SSH Key
        run: echo "${{ secrets.SSH_KEY }}" > ./id_rsa && chmod 600 ./id_rsa
      - name: Deploy Code
        run: SSH_KEY=./id_rsa ~/.composer/vendor/bin/envoy run deploy-code
