name: Deploy

on: [push]

jobs:
  deploy:
    name: Laravel Envoy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: composer install
      - run: ./vendor/bin/envoy run deploy-code
