name: Deploy

on: [push]

jobs:
  deploy:
    name: Laravel Envoy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: composer install
      - run: echo $SSH_KEY > ./id_rsa && chmod 600 ./id_rsa
      - run: cat ./id_rsa
      - run: SSH_KEY=./id_rsa ./vendor/bin/envoy run deploy-code
