name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
      - name: Set up variables
        run: |
          server="rias.be"
          userAndServer="forge@$server"
          repository="riasvdv/rias.be"
          baseDir="/home/forge/rias.be"
          releasesDir="$baseDir/releases"
          currentDir="$baseDir/current"
          newReleaseName="$(date +%F)-$(date +%H)$(date +%M)$(date +%S)"
          newReleaseDir="$releasesDir/$newReleaseName"
          user=$(whoami)

      - uses: appleboy/ssh-action@master
        name: Clone repository
        secrets:
          - KEY
        args:
          - "--host"
          - "$server"
          - "--script"
          - "[ -d $releasesDir ] || mkdir $releasesDir"
