name: Deploy

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run Envoy deploy
      run: |
        composer global require laravel/envoy
        envoy run deploy
